apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    role: database
    aggs2: database
spec:
  containers:
  - name: redis
    image: redis:latest
    command:
      - redis-server
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
  nodeSelector:
    aggs: db