apiVersion: v1
kind: Pod
metadata:
  name: aggregator-aggs
  labels:
    role: woker
    aggs2: aggregator
spec:
  containers:
    - name: aggregator
      image: aggs2:aggregator1
      ports:
        - name: aggs
          containerPort: 3000
          protocol: TCP
      args: ["10.96.240.207","3000","3000","0","500","1000","0"] # 10.100.104.221
  restartPolicy: OnFailure
  nodeSelector:
    aggs: agr
