apiVersion: v1
kind: Pod
metadata:
  name: verifier-aggs
  labels:
    role: woker     
    aggs2: verifier
spec:
  containers:
    - name: verifier
      image: aggs2:verifier1
      ports:
        - name: aggs
          containerPort: 3000
          protocol: TCP
      args: ["10.96.205.79","3000","0"]
  restartPolicy: OnFailure
  nodeSelector:
    aggs: vir
