apiVersion: v1
kind: Pod
metadata:
  name: aggregator-aggs
  labels:
    aggs2: aggregator
spec:
  containers:
    - name: aggregator
      image: 057607951461.dkr.ecr.ap-northeast-1.amazonaws.com/aggs2:aggregator6
      resources:
        limits:
          cpu: "63"
      ports:
      - name: aggs
        containerPort: 3000
        protocol: TCP
      args: ["10.100.211.153","3000","3000","0","500","64","1"] # 10.100.104.221
  restartPolicy: Never
  nodeSelector:
    aggs: agr
