apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    role: database
    aggs2: database
spec:
  containers:
  - name: redis
    image: 057607951461.dkr.ecr.ap-northeast-1.amazonaws.com/aggs2:redis
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "1"
    command:
      - redis-server
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
  nodeSelector:
    aggs: db