apiVersion: v1
kind: Pod
metadata:
  name: verifier-aggs
  labels:  
    aggs2: verifier
spec:
  containers:
    - name: verifier
      image: 057607951461.dkr.ecr.ap-northeast-1.amazonaws.com/aggs2:verifier16
      resources:
        limits:
          cpu: "63"
      ports:
      - name: aggs
        containerPort: 3000
        protocol: TCP
      args: ["10.100.240.24","3000","1"]
  restartPolicy: Never
  nodeSelector:
    aggs: vir
